# Generated by Django 3.2.12 on 2022-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20220525_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocomment',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communities.comment'),
            preserve_default=False,
        ),
    ]
