# Generated by Django 3.2.12 on 2022-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movie_id_movieimage_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='metacritic_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_average',
            field=models.FloatField(null=True),
        ),
    ]
