# Generated by Django 3.2.12 on 2022-05-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220519_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_sort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='movies.genresort'),
        ),
    ]
