# Generated by Django 3.2.12 on 2022-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220521_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres_id',
            new_name='genres',
        ),
    ]
