# Generated by Django 3.2.12 on 2022-05-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_genres_id_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='metacritic_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rotten_average',
        ),
        migrations.AddField(
            model_name='actor',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='en_overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('actor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField(null=True)),
                ('imdb_id', models.CharField(max_length=100, null=True)),
                ('profile_path', models.CharField(max_length=500, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('filmographies', models.ManyToManyField(related_name='directors', to='movies.Movie')),
            ],
        ),
    ]
