# Generated by Django 3.2.12 on 2022-05-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20220525_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=30)),
                ('owned_movies', models.ManyToManyField(related_name='OTTs', to='movies.Movie')),
            ],
        ),
    ]
