# Generated by Django 3.2.12 on 2022-05-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='actor_id',
            new_name='director_id',
        ),
    ]
