# Generated by Django 3.2.12 on 2022-05-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
