# Generated by Django 3.2.12 on 2022-05-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220519_0343'),
        ('accounts', '0002_auto_20220519_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_cnt', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='genre_counts',
            field=models.ManyToManyField(through='accounts.GenreCounts', to='movies.Genre'),
        ),
    ]
