# Generated by Django 3.2.12 on 2022-05-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_genres_id_movie_genres'),
        ('accounts', '0003_auto_20220520_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor_likes',
            field=models.ManyToManyField(related_name='liking_users', to='movies.Actor'),
        ),
    ]
