# Generated by Django 3.2.12 on 2022-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_genres_id_movie_genres'),
        ('accounts', '0005_alter_user_genre_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrecounts',
            old_name='genre',
            new_name='counted_genres',
        ),
        migrations.RenameField(
            model_name='genrecounts',
            old_name='user',
            new_name='recorded_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre_counts',
        ),
        migrations.AddField(
            model_name='user',
            name='counted_genres',
            field=models.ManyToManyField(related_name='recorded_user', through='accounts.GenreCounts', to='movies.Genre'),
        ),
    ]
