# Generated by Django 3.2.12 on 2022-05-24 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_genres_id_movie_genres'),
        ('accounts', '0006_auto_20220524_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_cnt', models.IntegerField(default=0)),
                ('counted_actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actor')),
                ('recorded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
