# Generated by Django 3.2.12 on 2022-05-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_actorcounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actorcounts',
            old_name='counted_actors',
            new_name='counted_actor',
        ),
        migrations.RenameField(
            model_name='genrecounts',
            old_name='counted_genres',
            new_name='counted_genre',
        ),
    ]
