# Generated by Django 3.2.12 on 2022-05-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_provider'),
        ('accounts', '0008_auto_20220524_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counted_actors',
            field=models.ManyToManyField(related_name='recorded_actor', through='accounts.ActorCounts', to='movies.Actor'),
        ),
    ]
