# Generated by Django 3.2.12 on 2022-05-19 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220519_0343'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='movie_likes',
            field=models.ManyToManyField(related_name='liking_users', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='movie_list',
            field=models.ManyToManyField(related_name='listing_users', to='movies.Movie'),
        ),
    ]
